USE arna_tours_travels;

-- Idempotent backend completion migration. Safe to run after schema.sql or on an existing installation.

CREATE TABLE IF NOT EXISTS drivers (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 full_name VARCHAR(150) NOT NULL,
 mobile_number VARCHAR(20) NOT NULL,
 email VARCHAR(150) NULL,
 license_number VARCHAR(80) NULL UNIQUE,
 vehicle_id INT UNSIGNED NULL,
 status ENUM('AVAILABLE','ASSIGNED','OFF_DUTY','INACTIVE') NOT NULL DEFAULT 'AVAILABLE',
 notes TEXT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_driver_status(status), INDEX idx_driver_name(full_name),
 CONSTRAINT fk_driver_vehicle FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL ON UPDATE CASCADE
);

DELIMITER $$
CREATE PROCEDURE arna_add_booking_columns()
BEGIN
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND COLUMN_NAME='vehicle_id') THEN
    ALTER TABLE bookings ADD COLUMN vehicle_id INT UNSIGNED NULL AFTER participants;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND COLUMN_NAME='driver_id') THEN
    ALTER TABLE bookings ADD COLUMN driver_id INT UNSIGNED NULL AFTER vehicle_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND INDEX_NAME='idx_booking_vehicle') THEN
    ALTER TABLE bookings ADD INDEX idx_booking_vehicle(vehicle_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND INDEX_NAME='idx_booking_driver') THEN
    ALTER TABLE bookings ADD INDEX idx_booking_driver(driver_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND CONSTRAINT_NAME='fk_booking_vehicle') THEN
    ALTER TABLE bookings ADD CONSTRAINT fk_booking_vehicle FOREIGN KEY(vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='bookings' AND CONSTRAINT_NAME='fk_booking_driver') THEN
    ALTER TABLE bookings ADD CONSTRAINT fk_booking_driver FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END$$
DELIMITER ;
CALL arna_add_booking_columns();
DROP PROCEDURE IF EXISTS arna_add_booking_columns;



