<?php
declare(strict_types=1);
require_once __DIR__ . '/admin-layout.php';
require_once __DIR__ . '/../models/Testimonial.php';
$m=new Testimonial(); $flash=getFlashMessage(); $message=$flash['message']??''; $type=$flash['type']??'success'; $editing=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{if(!verifyAdminCsrf())throw new RuntimeException('Security token expired. Refresh the page.');$action=$_POST['action']??'';$id=(int)($_POST['id']??0);
 if($action==='save'){ $name=trim((string)($_POST['customer_name']??''));$msg=trim((string)($_POST['message']??''));$rating=(int)($_POST['rating']??5);$status=(string)($_POST['status']??'ACTIVE'); if($name===''||$msg==='')throw new RuntimeException('Customer name and testimonial are required.');if($rating<1||$rating>5)throw new RuntimeException('Rating must be between 1 and 5.');if(!in_array($status,['ACTIVE','INACTIVE'],true))throw new RuntimeException('Invalid status.');$d=['customer_name'=>$name,'message'=>$msg,'rating'=>$rating,'status'=>$status];if($id){if(!$m->find($id))throw new RuntimeException('Testimonial not found.');$m->update($id,$d);$ok='Testimonial updated successfully.';}else{$m->create($d);$ok='Testimonial added successfully.';}setFlashMessage($ok);header('Location: testimonials.php');exit;}
 if($action==='delete'){if($id<1||!$m->find($id))throw new RuntimeException('Invalid testimonial.');$m->delete($id);setFlashMessage('Testimonial deleted successfully.');header('Location: testimonials.php');exit;}}catch(Throwable $e){$message=$e->getMessage();$type='danger';}}
if(isset($_GET['edit']))$editing=$m->find((int)$_GET['edit']);$rows=$m->all(false);$csrf=adminCsrfToken();adminHeader('Testimonials','Manage customer testimonials displayed on the public homepage.');?>
<div class="admin-card mb-4"><div class="admin-card-head"><div><h2><?= $editing?'Edit Testimonial':'Add Testimonial' ?></h2><p>Only ACTIVE testimonials appear on the homepage carousel.</p></div><?php if($editing):?><a class="btn-admin btn-light" href="testimonials.php">Cancel</a><?php endif;?></div><?php if($message):?><div class="px-4 pt-3"><div class="alert alert-<?=e($type)?> border-0 mb-0"><?=e($message)?></div></div><?php endif;?><form method="post" class="row g-3 p-4"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($editing['id']??0) ?>"><div class="col-md-6"><label class="form-label">Customer Name *</label><input class="form-control" name="customer_name" maxlength="150" required value="<?=e($editing['customer_name']??'')?>"></div><div class="col-md-3"><label class="form-label">Rating</label><select class="form-select" name="rating"><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>" <?=((int)($editing['rating']??5)===$i)?'selected':''?>><?=$i?> / 5</option><?php endfor;?></select></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="ACTIVE" <?=($editing['status']??'ACTIVE')==='ACTIVE'?'selected':''?>>Active</option><option value="INACTIVE" <?=($editing['status']??'')==='INACTIVE'?'selected':''?>>Inactive</option></select></div><div class="col-12"><label class="form-label">Testimonial *</label><textarea class="form-control" name="message" rows="5" maxlength="2000" required><?=e($editing['message']??'')?></textarea></div><div class="col-12"><button class="btn-admin btn-primary" type="submit"><i class="ri-save-line"></i><?=$editing?'Update Testimonial':'Add Testimonial'?></button></div></form></div>
<div class="admin-card"><div class="admin-card-head"><div><h2>Customer Testimonials</h2><p><?=count($rows)?> testimonial(s)</p></div></div><div class="table-responsive"><table class="table admin-table align-middle mb-0"><thead><tr><th>Customer</th><th>Testimonial</th><th>Rating</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=e($r['customer_name'])?></strong></td><td><?=e($r['message'])?></td><td><span class="text-warning"><?=str_repeat('★',(int)$r['rating'])?></span></td><td><span class="status-pill status-<?=strtolower($r['status'])?>"><?=e($r['status'])?></span></td><td class="text-end"><a class="btn-admin btn-light btn-sm" href="testimonials.php?edit=<?=(int)$r['id']?>">Edit</a> <form class="d-inline" method="post" onsubmit="return confirm('Delete this testimonial?')"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button class="btn-admin btn-danger-soft btn-sm" type="submit">Delete</button></form></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="text-center py-5 text-muted">No testimonials yet.</td></tr><?php endif;?></tbody></table></div></div><?php adminFooter();
